### ISSUE TITLE
Add support for custom domains

### ISSUE THREAD

**Issue by PachowStudios** [auth0-extensions/auth0-authentication-api-debugger-extension#18]
Please make the domain field editable so we can use the extension with custom domains. Most APIs validate the token issuer and the extension currently only allows me to get tokens using the default Auth0 domain, not my custom domain.

**Comment by PachowStudios** [comment]
Definitely still relevant. Could someone please take a look at this?

**Comment by arthurio** [comment]
I just faced the same issue, when requesting a JWT, the issuer (login domain) must match. Also, I tried making the input editable to set my own custom domain and it totally worked... So why not support it?

<img width="1750" alt="Auth0_-_Protocol_Debugger" src="https://user-images.githubusercontent.com/950449/145669004-a34367d3-e593-4e53-a08a-9968305abbe2.png">
